"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { ArrowDownIcon, ArrowUpIcon, DollarSign, ShoppingBag, CreditCard, PieChart } from "lucide-react"
import { Bar, BarChart, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, ResponsiveContainer } from "recharts"
import { ChartConfig, ChartContainer, ChartTooltipContent } from "@/components/ui/chart"

const chartConfig = {
  revenue: {
    label: "Revenue",
  },
  dineIn: {
    label: "Dine-in",
    color: "hsl(var(--chart-1))",
  },
  takeout: {
    label: "Takeout",
    color: "hsl(var(--chart-2))",
  },
  thirdParty: {
    label: "Third-Party",
    color: "hsl(var(--chart-3))",
  },
} satisfies ChartConfig

interface MacroViewProps {
  kpis: {
    netSales: { value: number; trend: number };
    orders: { value: number; trend: number };
    averageTicketSize: { value: number; trend: number };
    categoryDominance: { categoryName: string; percentage: number };
  };
  revenueClasses: Array<{ channel: string; revenue: number }>;
}

const formatTrend = (trend: number) => {
  if (trend === 0) return "0%"
  const sign = trend > 0 ? "+" : ""
  return `${sign}${trend.toFixed(1)}%`
}

export function MacroView({ kpis, revenueClasses }: MacroViewProps) {
  if (!kpis) return null

  const netSales = {
    label: "Net Sales",
    value: kpis.netSales?.value || 0,
    trend: formatTrend(kpis.netSales?.trend || 0),
    trendUp: (kpis.netSales?.trend || 0) >= 0,
  }

  const orders = {
    label: "Orders / Traffic",
    value: kpis.orders?.value || 0,
    trend: formatTrend(kpis.orders?.trend || 0),
    trendUp: (kpis.orders?.trend || 0) >= 0,
  }

  const aov = {
    label: "Avg. Ticket Size",
    value: kpis.averageTicketSize?.value || 0,
    trend: formatTrend(kpis.averageTicketSize?.trend || 0),
    trendUp: (kpis.averageTicketSize?.trend || 0) >= 0,
  }

  const categoryDominance = {
    label: "Category Dominance",
    category: kpis.categoryDominance?.categoryName || "N/A",
    description: kpis.categoryDominance?.categoryName 
      ? `${kpis.categoryDominance.percentage.toFixed(0)}% of Revenue generated by ${kpis.categoryDominance.categoryName}`
      : "No category data available",
  }

  const formattedRevenueClasses = revenueClasses?.map((rc) => {
    let colorKey = 'takeout'
    if (rc.channel === 'Dine-in') colorKey = 'dineIn'
    else if (rc.channel === 'Third-Party') colorKey = 'thirdParty'
    
    return {
      class: rc.channel,
      revenue: rc.revenue,
      fill: `var(--color-${colorKey})`,
    }
  }) || []

  return (
    <div className="mb-8 space-y-6">
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">{netSales.label}</CardTitle>
            <DollarSign className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">${netSales.value.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}</div>
            <p className="text-xs text-muted-foreground mt-1 flex items-center gap-1">
              <span className={netSales.trendUp ? "text-green-500" : "text-red-500"}>
                {netSales.trendUp ? <ArrowUpIcon className="h-3 w-3 inline" /> : <ArrowDownIcon className="h-3 w-3 inline" />}
                {netSales.trend}
              </span>{" "}
              vs last week
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">{orders.label}</CardTitle>
            <ShoppingBag className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{orders.value.toLocaleString()}</div>
            <p className="text-xs text-muted-foreground mt-1 flex items-center gap-1">
              <span className={orders.trendUp ? "text-green-500" : "text-red-500"}>
                {orders.trendUp ? <ArrowUpIcon className="h-3 w-3 inline" /> : <ArrowDownIcon className="h-3 w-3 inline" />}
                {orders.trend}
              </span>{" "}
              vs last week
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">{aov.label}</CardTitle>
            <CreditCard className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">${aov.value.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}</div>
            <p className="text-xs text-muted-foreground mt-1 flex items-center gap-1">
              <span className={aov.trendUp ? "text-green-500" : "text-red-500"}>
                {aov.trendUp ? <ArrowUpIcon className="h-3 w-3 inline" /> : <ArrowDownIcon className="h-3 w-3 inline" />}
                {aov.trend}
              </span>{" "}
              vs last week
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">{categoryDominance.label}</CardTitle>
            <PieChart className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{categoryDominance.category}</div>
            <p className="text-xs text-muted-foreground mt-1">
              {categoryDominance.description}
            </p>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Revenue Class Breakdown</CardTitle>
        </CardHeader>
        <CardContent>
          <ChartContainer config={chartConfig} className="h-[200px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={formattedRevenueClasses} margin={{ top: 20, right: 20, left: 20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey="class" axisLine={false} tickLine={false} tickMargin={10} />
                <YAxis 
                  type="number" 
                  axisLine={false} 
                  tickLine={false} 
                  tickFormatter={(value) => `$${value / 1000}k`} 
                />
                <RechartsTooltip cursor={{fill: 'transparent'}} content={<ChartTooltipContent hideLabel />} />
                <Bar dataKey="revenue" radius={[4, 4, 0, 0]} barSize={40} />
              </BarChart>
            </ResponsiveContainer>
          </ChartContainer>
        </CardContent>
      </Card>
    </div>
  )
}
