export const macroData = {
  netSales: { value: 124500, label: "Net Sales", trend: "+12%", trendUp: true },
  orders: { value: 3240, label: "Orders / Traffic", trend: "+5%", trendUp: true },
  aov: { value: 38.42, label: "Avg. Ticket Size", trend: "-1.2%", trendUp: false },
  categoryDominance: {
    category: "Sushi Rolls",
    percentage: 42,
    label: "Category Dominance",
    description: "42% of Revenue generated by Sushi Rolls",
  },
}

export const revenueClassData = [
  { class: "Dine-in", revenue: 65000, fill: "var(--color-dineIn)" },
  { class: "Takeout", revenue: 35000, fill: "var(--color-takeout)" },
  { class: "Third-Party", revenue: 24500, fill: "var(--color-thirdParty)" },
]

export const masterItemsData = [
  { id: "1", name: "Spicy Tuna Roll", category: "Sushi Rolls", price: 12.00, unitsSold: 450, totalRevenue: 5400, guestMentions: 12, trend: "+45%", trendUp: true },
  { id: "2", name: "Salmon Nigiri", category: "Nigiri & Sashimi", price: 14.00, unitsSold: 420, totalRevenue: 5880, guestMentions: 8, trend: "+12%", trendUp: true },
  { id: "3", name: "Edamame", category: "Appetizers", price: 6.00, unitsSold: 380, totalRevenue: 2280, guestMentions: 2, trend: "+5%", trendUp: true },
  { id: "4", name: "California Roll", category: "Sushi Rolls", price: 10.00, unitsSold: 350, totalRevenue: 3500, guestMentions: 5, trend: "-2%", trendUp: false },
  { id: "5", name: "Miso Soup", category: "Appetizers", price: 4.00, unitsSold: 300, totalRevenue: 1200, guestMentions: 1, trend: "+1%", trendUp: true },
  { id: "6", name: "Dragon Roll", category: "Sushi Rolls", price: 16.00, unitsSold: 280, totalRevenue: 4480, guestMentions: 15, trend: "+8%", trendUp: true },
  { id: "7", name: "Yellowtail Sashimi", category: "Nigiri & Sashimi", price: 18.00, unitsSold: 150, totalRevenue: 2700, guestMentions: 4, trend: "-5%", trendUp: false },
  { id: "8", name: "Shrimp Tempura", category: "Appetizers", price: 9.00, unitsSold: 210, totalRevenue: 1890, guestMentions: 3, trend: "+10%", trendUp: true },
  { id: "9", name: "Spider Roll", category: "Sushi Rolls", price: 15.00, unitsSold: 190, totalRevenue: 2850, guestMentions: 7, trend: "+2%", trendUp: true },
  { id: "10", name: "Tuna Sashimi", category: "Nigiri & Sashimi", price: 16.00, unitsSold: 180, totalRevenue: 2880, guestMentions: 6, trend: "-1%", trendUp: false },
  { id: "11", name: "Octopus Sashimi", category: "Nigiri & Sashimi", price: 18.00, unitsSold: 45, totalRevenue: 810, guestMentions: 0, trend: "-20%", trendUp: false },
  { id: "12", name: "Uni (Sea Urchin)", category: "Nigiri & Sashimi", price: 22.00, unitsSold: 30, totalRevenue: 660, guestMentions: 2, trend: "-15%", trendUp: false },
  { id: "13", name: "Tempura Udon", category: "Noodles", price: 16.00, unitsSold: 85, totalRevenue: 1360, guestMentions: 1, trend: "-8%", trendUp: false },
  { id: "14", name: "Soft Shell Crab", category: "Appetizers", price: 15.00, unitsSold: 90, totalRevenue: 1350, guestMentions: 0, trend: "-5%", trendUp: false },
  { id: "15", name: "Green Tea Mochi", category: "Desserts", price: 5.00, unitsSold: 120, totalRevenue: 600, guestMentions: 4, trend: "0%", trendUp: true },
]

export const guestFeedbackData = {
  "1": [
    { source: "Yelp", rating: 5, date: "2023-10-28", text: "The Spicy Tuna Roll is absolutely incredible! Perfect amount of heat." },
    { source: "Google", rating: 4, date: "2023-10-25", text: "Spicy tuna roll was good but a bit too much mayo." },
    { source: "Yelp", rating: 5, date: "2023-10-20", text: "Best spicy tuna roll in the city." },
  ],
  "6": [
    { source: "Google", rating: 5, date: "2023-10-27", text: "Dragon roll is a must-have!" },
    { source: "Yelp", rating: 3, date: "2023-10-22", text: "Dragon roll was slightly smaller than expected for the price." },
  ]
}
